export const initialThemes = [
  {
    "id": "fashion-01",
    "demoNumber": "Demo 01",
    "name": "Fashion Store 01",
    "category": "Fashion & Apparel",
    "version": "v1.4.2",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 428,
    "rating": 4.9,
    "demoPath": "/",
    "thumbnail": "/assets/imgs/page/homepage1/banner.png",
    "bundleKey": "theme.store.fashion01.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-20",
    "description": "Tata letak storefront fashion utama dengan hero slider besar, etalase kategori cepat, dan galeri produk grid.",
    "features": [
      "Hero Slider Video/Img",
      "Sticky Header Filter",
      "Instagram Shopping Feed",
      "Mega Menu 4 Kolom"
    ]
  },
  {
    "id": "fashion-02",
    "demoNumber": "Demo 02",
    "name": "Fashion Store 02",
    "category": "Fashion & Apparel",
    "version": "v1.3.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 312,
    "rating": 4.8,
    "demoPath": "/index-2",
    "thumbnail": "/assets/imgs/page/homepage2/banner.png",
    "bundleKey": "theme.store.fashion02.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-15",
    "description": "Estetika streetwear kontemporer dengan tipografi bold, banner asimetris, dan penyorotan koleksi musiman.",
    "features": [
      "Bold Typography Hero",
      "Lookbook Pin Tags",
      "Countdown Flash Deal",
      "Infinite Scroll Collection"
    ]
  },
  {
    "id": "fashion-03",
    "demoNumber": "Demo 03",
    "name": "Fashion Store 03",
    "category": "Fashion & Apparel",
    "version": "v1.2.5",
    "status": "PREMIUM",
    "price": 199000,
    "activeMerchantsCount": 184,
    "rating": 4.9,
    "demoPath": "/index-3",
    "thumbnail": "/assets/imgs/page/homepage3/banner.png",
    "bundleKey": "theme.store.fashion03.v1",
    "isGlobalEnabled": true,
    "author": "Studio Luxe Paris",
    "updatedAt": "2026-08-10",
    "description": "Nuansa editorial mewah untuk desainer busana dan butik premium dengan transisi halaman lembut.",
    "features": [
      "Editorial Lookbook Grid",
      "Quick Add-to-Cart Drawer",
      "Video Story Showcase",
      "Multi-Currency Ready"
    ]
  },
  {
    "id": "fashion-04",
    "demoNumber": "Demo 04",
    "name": "Fashion Store 04",
    "category": "Fashion & Apparel",
    "version": "v1.1.8",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 220,
    "rating": 4.7,
    "demoPath": "/index-4",
    "thumbnail": "/assets/imgs/page/homepage4/banner.png",
    "bundleKey": "theme.store.fashion04.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-07-28",
    "description": "Tema monokrom kontras tinggi dengan fokus tajam pada fotografi pakaian dan tekstur bahan.",
    "features": [
      "Monochrome Palettes",
      "High Contrast Detail View",
      "Product Hover Preview",
      "Size Chart Popover"
    ]
  },
  {
    "id": "fashion-05",
    "demoNumber": "Demo 05",
    "name": "Fashion Store 05",
    "category": "Fashion & Apparel",
    "version": "v1.2.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 165,
    "rating": 4.7,
    "demoPath": "/index-5",
    "thumbnail": "/assets/imgs/page/homepage5/banner.png",
    "bundleKey": "theme.store.fashion05.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-07-15",
    "description": "Palet warna cerah dan ceria untuk fashion anak muda, gaun pesta, dan aksesoris festive.",
    "features": [
      "Pastel & Vibrant Accents",
      "Sale Badge Animations",
      "Interactive Swatches",
      "Sticky Cart Bar"
    ]
  },
  {
    "id": "fashion-06",
    "demoNumber": "Demo 06",
    "name": "Fashion Store 06",
    "category": "Fashion & Apparel",
    "version": "v1.0.9",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 98,
    "rating": 4.6,
    "demoPath": "/index-6",
    "thumbnail": "/assets/imgs/page/homepage6/collection1.png",
    "bundleKey": "theme.store.fashion06.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-06-30",
    "description": "Nuansa klasik untuk toko thrift shop, baju vintage, dan karya fesyen retro autentik.",
    "features": [
      "Vintage Stamp Badges",
      "Thrift Single Item Notice",
      "Story Timeline Blog",
      "Sepia Graders"
    ]
  },
  {
    "id": "underwear-07",
    "demoNumber": "Demo 07",
    "name": "Underwear Store",
    "category": "Fashion & Apparel",
    "version": "v1.1.4",
    "status": "PREMIUM",
    "price": 149000,
    "activeMerchantsCount": 142,
    "rating": 4.9,
    "demoPath": "/index-7",
    "thumbnail": "/assets/imgs/page/homepage7/banner.png",
    "bundleKey": "theme.store.underwear.v1",
    "isGlobalEnabled": true,
    "author": "Studio Luxe Paris",
    "updatedAt": "2026-07-02",
    "description": "Desain elegan dan lembut khusus pakaian santai di rumah, pakaian dalam sutra, dan piyama premium.",
    "features": [
      "Subtle Warm Tones",
      "Confidential Shipping Notice",
      "Size Advisor Widget",
      "Smooth Image Zoom"
    ]
  },
  {
    "id": "furniture-08",
    "demoNumber": "Demo 08",
    "name": "Furniture Store 01",
    "category": "Home & Furniture",
    "version": "v1.4.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 310,
    "rating": 4.8,
    "demoPath": "/index-8",
    "thumbnail": "/assets/imgs/page/homepage8/chair.png",
    "bundleKey": "theme.store.furniture01.v1",
    "isGlobalEnabled": true,
    "author": "ScandiCraft Studio",
    "updatedAt": "2026-08-16",
    "description": "Katalog perabotan kayu solid Skandinavia dengan 3D room preview, spesifikasi dimensi kayu, dan estimasi kargo.",
    "features": [
      "Room Ambience Visualizer",
      "Wood Finish Swatch Selector",
      "Bulky Cargo Shipping Calc",
      "Assembly Manual Download"
    ]
  },
  {
    "id": "furniture-09",
    "demoNumber": "Demo 09",
    "name": "Furniture Store 02",
    "category": "Home & Furniture",
    "version": "v1.3.2",
    "status": "PREMIUM",
    "price": 229000,
    "activeMerchantsCount": 175,
    "rating": 4.9,
    "demoPath": "/index-9",
    "thumbnail": "/assets/imgs/page/homepage9/banner.png",
    "bundleKey": "theme.store.furniture02.v1",
    "isGlobalEnabled": true,
    "author": "Studio Loft Milan",
    "updatedAt": "2026-08-22",
    "description": "Konsep perabotan industrial apartemen modern dengan palet warna earthy, beton, dan logam hitam matte.",
    "features": [
      "Interior Blueprint View",
      "Custom Modular Configurator",
      "High-Resolution Zoom",
      "B2B Project Inquiry Form"
    ]
  },
  {
    "id": "homeliving-10",
    "demoNumber": "Demo 10",
    "name": "Home Living",
    "category": "Home & Furniture",
    "version": "v1.2.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 290,
    "rating": 4.8,
    "demoPath": "/index-10",
    "thumbnail": "/assets/imgs/page/homepage10/banner.jpg",
    "bundleKey": "theme.store.homeliving.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-07-29",
    "description": "Dekorasi rumah, sprei tidur, pencahayaan lilin aromaterapi, dan pernak-pernik kenyamanan hunian.",
    "features": [
      "Color Palette Filter",
      "Home Stylist Curated Bundles",
      "Gift Wrapping Option",
      "Customer Photo Reviews"
    ]
  },
  {
    "id": "pets-11",
    "demoNumber": "Demo 11",
    "name": "Pets Store",
    "category": "Pets & Animals",
    "version": "v1.4.1",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 260,
    "rating": 4.9,
    "demoPath": "/index-11",
    "thumbnail": "/assets/imgs/page/homepage11/pets.png",
    "bundleKey": "theme.store.pets.v1",
    "isGlobalEnabled": true,
    "author": "PetLovers Creative",
    "updatedAt": "2026-08-14",
    "description": "Toko perlengkapan hewan peliharaan (anjing, kucing, ikan, burung) dengan kalkulator pakan berat badan dan jadwal langganan.",
    "features": [
      "Pet Breed & Weight Filter",
      "Subscription Autoship Toggle",
      "Nutrition Facts Panel",
      "Pet Community Forum"
    ]
  },
  {
    "id": "organic-12",
    "demoNumber": "Demo 12",
    "name": "Oganic Store",
    "category": "Food & Beverages",
    "version": "v1.3.5",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 205,
    "rating": 4.8,
    "demoPath": "/index-12",
    "thumbnail": "/assets/imgs/page/homepage12/banner.png",
    "bundleKey": "theme.store.organic.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-05",
    "description": "Toko sayur mayur organik, buah segar hidroponik, dan produk pangan ramah lingkungan dari petani langsung.",
    "features": [
      "Same-Day Delivery Timer",
      "Organic Certification Badges",
      "Farm Origin Tracker",
      "Weight (Gram/Kg) Selector"
    ]
  },
  {
    "id": "toys-13",
    "demoNumber": "Demo 13",
    "name": "Toys Store",
    "category": "Kids & Toys",
    "version": "v1.2.8",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 190,
    "rating": 4.8,
    "demoPath": "/index-13",
    "thumbnail": "/assets/imgs/page/homepage13/banner.png",
    "bundleKey": "theme.store.toys.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-07-22",
    "description": "Etalase mainan edukasi anak, action figures, board games, dan permainan keluarga dengan warna ceria dan filter usia.",
    "features": [
      "Age Range Filter (0-2, 3-5, 6+)",
      "Interactive Toy Video Demos",
      "Safety SNI Certificate Badge",
      "Gift Registry Wishlist"
    ]
  },
  {
    "id": "skateboard-14",
    "demoNumber": "Demo 14",
    "name": "Skateboard Store",
    "category": "Sports & Outdoors",
    "version": "v1.2.2",
    "status": "PREMIUM",
    "price": 179000,
    "activeMerchantsCount": 140,
    "rating": 4.8,
    "demoPath": "/index-14",
    "thumbnail": "/assets/imgs/page/homepage14/banner.jpg",
    "bundleKey": "theme.store.skateboard.v1",
    "isGlobalEnabled": true,
    "author": "RiderZone Studio",
    "updatedAt": "2026-08-11",
    "description": "Papan skateboard, deck kustom, trucks, wheels, dan pakaian komunitas extreme street sports.",
    "features": [
      "Custom Deck Builder App",
      "Grip Tape Graphic Selector",
      "Skate Team Member Bios",
      "Action Reel Highlights"
    ]
  },
  {
    "id": "skincare-15",
    "demoNumber": "Demo 15",
    "name": "Natural Skins",
    "category": "Beauty & Skincare",
    "version": "v1.4.1",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 350,
    "rating": 4.9,
    "demoPath": "/index-15",
    "thumbnail": "/assets/imgs/page/homepage15/banner.png",
    "bundleKey": "theme.store.naturalskins.v1",
    "isGlobalEnabled": true,
    "author": "GlowAesthetic Lab",
    "updatedAt": "2026-08-28",
    "description": "Desain bersih dan tenang untuk produk serum kecantikan, skincare organik dengan sertifikat BPOM & Halal.",
    "features": [
      "Skin Type Routine Quiz",
      "BPOM Badge Integration",
      "Ingredients Breakdown Accordion",
      "Before/After Slider"
    ]
  },
  {
    "id": "electronic-16",
    "demoNumber": "Demo 16",
    "name": "Electronic",
    "category": "Electronics & Gadgets",
    "version": "v1.5.1",
    "status": "PREMIUM",
    "price": 289000,
    "activeMerchantsCount": 395,
    "rating": 4.9,
    "demoPath": "/index-16",
    "thumbnail": "/assets/imgs/page/homepage16/banner.png",
    "bundleKey": "theme.store.electronic.v1",
    "isGlobalEnabled": true,
    "author": "TechVenture Dev",
    "updatedAt": "2026-09-02",
    "description": "Template e-commerce elektronik masif dengan filter multi-spesifikasi (RAM, Processor, Garansi Resmi), flash sale, dan komparasi spek produk berdampingan.",
    "features": [
      "Spec Comparison Table",
      "Installment Payment Calc",
      "Serial Number Warranty Checker",
      "Mega Navigation Matrix"
    ]
  },
  {
    "id": "food-17",
    "demoNumber": "Demo 17",
    "name": "Food Store",
    "category": "Food & Beverages",
    "version": "v1.3.3",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 280,
    "rating": 4.8,
    "demoPath": "/index-17",
    "thumbnail": "/assets/imgs/page/homepage17/banner.png",
    "bundleKey": "theme.store.food.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-08",
    "description": "Etalase makanan ringan, saus premium, kopi kemasan, dan produk kuliner UMKM lokal.",
    "features": [
      "Expiry Date Display",
      "Instant Delivery Courier Tag",
      "Halal & P-IRT Badge",
      "Flavor Variant Swatches"
    ]
  },
  {
    "id": "fashion-18",
    "demoNumber": "Demo 18",
    "name": "Fashion Store 08",
    "category": "Fashion & Apparel",
    "version": "v1.2.1",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 175,
    "rating": 4.8,
    "demoPath": "/index-18",
    "thumbnail": "/assets/imgs/page/homepage18/banner.png",
    "bundleKey": "theme.store.fashion08.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-01",
    "description": "Nuansa tropis dan liburan pantai untuk pakaian renang, kacamata hitam, dan pakaian musim panas.",
    "features": [
      "Tropical Visual Themes",
      "Seasonal Promo Bar",
      "Waterproof Badge Highlight",
      "Review Star Carousel"
    ]
  },
  {
    "id": "plants-19",
    "demoNumber": "Demo 19",
    "name": "Plants Store",
    "category": "Home & Gardening",
    "version": "v1.3.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 185,
    "rating": 4.9,
    "demoPath": "/index-19",
    "thumbnail": "/assets/imgs/page/homepage19/banner.png",
    "bundleKey": "theme.store.plants.v1",
    "isGlobalEnabled": true,
    "author": "Botanica Creative",
    "updatedAt": "2026-08-19",
    "description": "Nursery tanaman hias indoor/outdoor, pot keramik artisan, pupuk organik, dan panduan perawatan tanaman hidup.",
    "features": [
      "Sunlight & Watering Needs Badges",
      "Plant Care Guide Tab",
      "Fragile Plant Packaging Notice",
      "Pot Sizing Selector"
    ]
  },
  {
    "id": "bikes-20",
    "demoNumber": "Demo 20",
    "name": "Bikes Store",
    "category": "Sports & Outdoors",
    "version": "v1.3.4",
    "status": "PREMIUM",
    "price": 219000,
    "activeMerchantsCount": 165,
    "rating": 4.8,
    "demoPath": "/index-20",
    "thumbnail": "/assets/imgs/page/homepage20/banner.png",
    "bundleKey": "theme.store.bikes.v1",
    "isGlobalEnabled": true,
    "author": "CycleLab Global",
    "updatedAt": "2026-08-26",
    "description": "Sepeda balap road bike, gravel, mountain bike (MTB), serta spare part groupset dan perlengkapan pesepeda.",
    "features": [
      "Frame Size (cm) Recommender",
      "Groupset Spec Selector",
      "Bike Fitting Appointment",
      "Financing & Cicilan Module"
    ]
  },
  {
    "id": "baby-21",
    "demoNumber": "Demo 21",
    "name": "Baby Clothing",
    "category": "Kids & Maternity",
    "version": "v1.2.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 240,
    "rating": 4.9,
    "demoPath": "/index-21",
    "thumbnail": "/assets/imgs/page/homepage21/banner.png",
    "bundleKey": "theme.store.baby.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-02",
    "description": "Pakaian bayi newborn, baju ibu menyusui, stroller bayi, dan perlengkapan higienis bersertifikasi hypoallergenic.",
    "features": [
      "Hypoallergenic Badge",
      "Baby Age Month Filter",
      "Hospital Bag Checklist",
      "Soft Pastel Color Mode"
    ]
  },
  {
    "id": "fashion-22",
    "demoNumber": "Demo 22",
    "name": "Fashion Store 09",
    "category": "Fashion & Apparel",
    "version": "v1.3.0",
    "status": "PREMIUM",
    "price": 189000,
    "activeMerchantsCount": 230,
    "rating": 4.9,
    "demoPath": "/index-22",
    "thumbnail": "/assets/imgs/page/homepage22/banner.png",
    "bundleKey": "theme.store.fashion09.v1",
    "isGlobalEnabled": true,
    "author": "ActiveVibe Lab",
    "updatedAt": "2026-08-18",
    "description": "Desain dinamis berkecepatan tinggi untuk pakaian olahraga gym, jersey lari, dan pakaian training.",
    "features": [
      "Dynamic Action Sliders",
      "Breathable Fabric Spec Badges",
      "Bundle Buy Discount",
      "Coach Review Section"
    ]
  },
  {
    "id": "travel-23",
    "demoNumber": "Demo 23",
    "name": "Travel gear",
    "category": "Travel & Outdoor",
    "version": "v1.2.9",
    "status": "PREMIUM",
    "price": 199000,
    "activeMerchantsCount": 170,
    "rating": 4.8,
    "demoPath": "/index-23",
    "thumbnail": "/assets/imgs/page/homepage23/banner.png",
    "bundleKey": "theme.store.travelgear.v1",
    "isGlobalEnabled": true,
    "author": "GlobeTrekker Co",
    "updatedAt": "2026-08-21",
    "description": "Koper cabin size, tas backpack travel anti-maling, aksesori adaptor paspor, dan perlengkapan petualang global.",
    "features": [
      "Airline Cabin Size Compatibility Check",
      "TSA Lock Info Modal",
      "Weatherproof Tag",
      "Warranty Lifetime Badge"
    ]
  },
  {
    "id": "coffee-24",
    "demoNumber": "Demo 24",
    "name": "Coffee Shop",
    "category": "Food & Beverages",
    "version": "v1.4.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 310,
    "rating": 5,
    "demoPath": "/index-24",
    "thumbnail": "/assets/imgs/page/homepage24/banner.png",
    "bundleKey": "theme.store.coffeeshop.v1",
    "isGlobalEnabled": true,
    "author": "RoastMasters Studio",
    "updatedAt": "2026-08-30",
    "description": "Roastery biji kopi spesialti (Arabika/Robusta nusantara), alat seduh manual brew (V60, Aeropress), dan langganan kopi segar bulanan.",
    "features": [
      "Tasting Notes Flavor Wheel",
      "Roast Level Slider (Light/Med/Dark)",
      "Grind Size Options (Whole/Fine/Coarse)",
      "Roasting Date Guarantee"
    ]
  },
  {
    "id": "fashion-25",
    "demoNumber": "Demo 25",
    "name": "Fashion Store 07",
    "category": "Fashion & Apparel",
    "version": "v1.1.2",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 110,
    "rating": 4.7,
    "demoPath": "/index-25",
    "thumbnail": "/assets/imgs/page/homepage25/banner.jpg",
    "bundleKey": "theme.store.fashion07.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-06-18",
    "description": "Koleksi jaket musim dingin, coat wol, sweater rajut, dan syal dengan suasana dingin Skandinavia.",
    "features": [
      "Frost Glassmorphism Cards",
      "Material Warmth Indicator",
      "Stock Scarcity Warning",
      "Lookbook Gallery"
    ]
  },
  {
    "id": "shoes-26",
    "demoNumber": "Demo 26",
    "name": "Shoes",
    "category": "Footwear & Shoes",
    "version": "v1.4.0",
    "status": "PREMIUM",
    "price": 249000,
    "activeMerchantsCount": 380,
    "rating": 5,
    "demoPath": "/index-26",
    "thumbnail": "/assets/imgs/page/homepage26/banner.png",
    "bundleKey": "theme.store.shoes.v1",
    "isGlobalEnabled": true,
    "author": "KicksNation Dev",
    "updatedAt": "2026-09-01",
    "description": "Tema khusus sneakerhead dengan drop countdown, raffle kupon, dan 360-derajat visualizer sepatu.",
    "features": [
      "Sneaker Drop Timer",
      "EU/US/CM Size Converter",
      "360 Image Orbit Preview",
      "Verified Authentic Seal"
    ]
  },
  {
    "id": "phonecases-27",
    "demoNumber": "Demo 27",
    "name": "Phonecases",
    "category": "Electronics & Gadgets",
    "version": "v1.2.3",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 275,
    "rating": 4.8,
    "demoPath": "/index-27",
    "thumbnail": "/assets/imgs/page/homepage27/banner.png",
    "bundleKey": "theme.store.phonecases.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-12",
    "description": "Casing smartphone custom, pelindung layar tempered glass, charger MagSafe, dan aksesoris gadget trendi.",
    "features": [
      "Phone Model Dropdown Filter (iPhone/Samsung)",
      "Drop Test Protection Rating",
      "MagSafe Indicator",
      "Live Case Mockup"
    ]
  },
  {
    "id": "yoga-28",
    "demoNumber": "Demo 28",
    "name": "Yoga Clothing",
    "category": "Health & Wellness",
    "version": "v1.3.1",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 195,
    "rating": 4.9,
    "demoPath": "/index-28",
    "thumbnail": "/assets/imgs/page/homepage28/banner.png",
    "bundleKey": "theme.store.yogaclothing.v1",
    "isGlobalEnabled": true,
    "author": "Zenith Flow Studio",
    "updatedAt": "2026-08-24",
    "description": "Pakaian yoga stretchable, matras yoga eco-friendly, resistance band, dan aksesoris meditasi.",
    "features": [
      "Material Stretch Indicator (4-way)",
      "Eco-Friendly Certification",
      "Instructor Picks Showcase",
      "Calm Nature Audio Loop"
    ]
  },
  {
    "id": "jewelry-29",
    "demoNumber": "Demo 29",
    "name": "Jewelry Store",
    "category": "Luxury & Jewelry",
    "version": "v1.3.1",
    "status": "PREMIUM",
    "price": 269000,
    "activeMerchantsCount": 160,
    "rating": 4.9,
    "demoPath": "/index-29",
    "thumbnail": "/assets/imgs/page/homepage29/banner.png",
    "bundleKey": "theme.store.jewelry.v1",
    "isGlobalEnabled": true,
    "author": "Maison Brilliance",
    "updatedAt": "2026-08-27",
    "description": "Koleksi perhiasan emas putih, cincin tunangan berlian, kalung mutiara air tawar, dan sertifikat keaslian GIA.",
    "features": [
      "Carat & Clarity Guide",
      "Virtual Ring Size Measurer",
      "Certificate Verification Link",
      "Insured Shipping Badge"
    ]
  },
  {
    "id": "socks-30",
    "demoNumber": "Demo 30",
    "name": "Socks Store",
    "category": "Fashion & Apparel",
    "version": "v1.1.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 180,
    "rating": 4.7,
    "demoPath": "/index-30",
    "thumbnail": "/assets/imgs/page/homepage30/banner.png",
    "bundleKey": "theme.store.socks.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-07-10",
    "description": "Kaos kaki motif ceria, compression socks untuk pelari, dan paket bundle hemat multipack.",
    "features": [
      "Bundle 3-Pack Builder",
      "Pattern Swatches Preview",
      "Anti-Bacterial Fabric Badge",
      "Quick Gift Box Addon"
    ]
  },
  {
    "id": "watch-31",
    "demoNumber": "Demo 31",
    "name": "Watch Store",
    "category": "Luxury & Jewelry",
    "version": "v1.5.0",
    "status": "PREMIUM",
    "price": 299000,
    "activeMerchantsCount": 215,
    "rating": 5,
    "demoPath": "/index-31",
    "thumbnail": "/assets/imgs/page/homepage31/banner.png",
    "bundleKey": "theme.store.watch.v1",
    "isGlobalEnabled": true,
    "author": "Geneva Horology Studio",
    "updatedAt": "2026-09-05",
    "description": "Desain ultra-luxury dark mode dengan detail spesifikasi kaliber mesin jam, strap customizer, dan garansi resmi.",
    "features": [
      "Dark Mode Luxury Theme",
      "Movement Spec Sheet Accordion",
      "Official Warranty Registration",
      "Escrow High-Value Badge"
    ]
  },
  {
    "id": "books-32",
    "demoNumber": "Demo 32",
    "name": "Book Store",
    "category": "Books & Stationery",
    "version": "v1.2.0",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 195,
    "rating": 4.8,
    "demoPath": "/index-32",
    "thumbnail": "/assets/imgs/page/homepage32/banner.png",
    "bundleKey": "theme.store.bookstore.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-03",
    "description": "Toko buku online, novel best seller, buku pengembangan diri, komik, dan alat tulis premium.",
    "features": [
      "Book Excerpt Preview",
      "Author Bio Section",
      "ISBN & Publisher Filter",
      "Hardcover vs Paperback Toggle"
    ]
  },
  {
    "id": "glasses-33",
    "demoNumber": "Demo 33",
    "name": "Glasses Shop",
    "category": "Accessories & Eyewear",
    "version": "v1.2.7",
    "status": "PUBLIC_FREE",
    "price": 0,
    "activeMerchantsCount": 190,
    "rating": 4.8,
    "demoPath": "/index-33",
    "thumbnail": "/assets/imgs/page/homepage33/banner.png",
    "bundleKey": "theme.store.glassesshop.v1",
    "isGlobalEnabled": true,
    "author": "Indovia Design Lab",
    "updatedAt": "2026-08-09",
    "description": "Frame kacamata baca minus/silinder, lensa anti radiasi blueray, dan sunglasses gaya retro musim panas.",
    "features": [
      "Face Shape Frame Guide",
      "Prescription Lens Upload",
      "Virtual Mirror Try-on Tag",
      "Polarized Lens Badge"
    ]
  },
  {
    "id": "jeans-34",
    "demoNumber": "Demo 34",
    "name": "Jeans Fashion",
    "category": "Fashion & Apparel",
    "version": "v1.2.4",
    "status": "PREMIUM",
    "price": 159000,
    "activeMerchantsCount": 195,
    "rating": 4.9,
    "demoPath": "/index-34",
    "thumbnail": "/assets/imgs/page/homepage34/banner.jpg",
    "bundleKey": "theme.store.jeansfashion.v1",
    "isGlobalEnabled": true,
    "author": "Heritage Crafters",
    "updatedAt": "2026-08-25",
    "description": "Tata letak industrialis maskulin khusus celana jeans selvedge, jaket denim, dan kerajinan kulit lokal.",
    "features": [
      "Denim Weight (Oz) Filter",
      "Fading Evolution Slider",
      "Custom Inseam Size Selector",
      "Workshop Story Page"
    ]
  }
];

// MASTER MODULAR SECTIONS & STORE PAGES REGISTRY
export const initialSections = [
  {
    key: 'TOP_ANNOUNCEMENT_BAR',
    name: 'Pita Pengumuman Promo (Announcement Bar)',
    code: 'announcement_bar',
    category: 'Header & Notifikasi',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 780,
    systemDependency: 'None (Pure CSS/React)',
    latencyRating: 'Ultra Fast (<5ms)',
    description: 'Pita notifikasi baris teratas untuk menyiarkan informasi gratis ongkir, kode kupon diskon toko, atau pengumuman hari libur operasional.',
    defaultSchema: {
      text: '🎉 PROMO SPESIAL: Bebas Ongkir ke Seluruh Indonesia min. belanja Rp 100.000 dengan kode INDOVIAHEMAT',
      backgroundColor: '#111827',
      textColor: '#ffffff',
      showCloseButton: true,
      enableCountdown: true,
      countdownEndTime: '2026-12-31T23:59:59Z',
      actionUrl: '/shop-left-filter.html'
    }
  },
  {
    key: 'HERO_SLIDER_BANNER',
    name: 'Banner Slider Utama (Hero Banner)',
    code: 'hero_slider',
    category: 'Hero & Visual',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 840,
    systemDependency: 'Swiper Engine v11',
    latencyRating: 'Fast (<15ms)',
    description: 'Slide visual utama beresolusi tinggi dengan dukungan video loop latar, animasi teks bergerak, dan tombol ajakan bertindak (CTA).',
    defaultSchema: {
      autoPlay: true,
      intervalSeconds: 5,
      transitionEffect: 'fade',
      maxSlidesAllowed: 5,
      heightDesktopPx: 560,
      heightMobilePx: 380,
      showDotsPagination: true,
      showArrowNav: true
    }
  },
  {
    key: 'FLASH_SALE_COUNTDOWN',
    name: 'Penawaran Kilat & Timer Mundur (Flash Sale)',
    code: 'flash_sale',
    category: 'Promosi & Konversi',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 620,
    systemDependency: 'Redis Realtime Clock Engine',
    latencyRating: 'Real-time (<20ms)',
    description: 'Etalase produk diskon spesial dengan timer hitung mundur dan progress bar ketersediaan kuota stok produk.',
    defaultSchema: {
      maxProductsDisplay: 8,
      showStockProgressBar: true,
      autoHideWhenExpired: true,
      discountBadgeColor: '#ef4444',
      timerStyle: 'flip_clock_modern',
      requireInventorySync: true
    }
  },
  {
    key: 'DYNAMIC_CATEGORY_CAROUSEL',
    name: 'Kategori Produk Interaktif (Category Carousel)',
    code: 'category_carousel',
    category: 'Navigasi Produk',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 810,
    systemDependency: 'Indovia Catalog Cache',
    latencyRating: 'Ultra Fast (<8ms)',
    description: 'Galeri ikon dan thumbnail kategori yang bisa digeser dengan mulus untuk mempercepat navigasi belanja pengunjung.',
    defaultSchema: {
      displayStyle: 'circle_rounded',
      itemsPerViewDesktop: 6,
      itemsPerViewMobile: 3,
      showProductCountBadge: true,
      grayscaleHoverEffect: true
    }
  },
  {
    key: 'BEST_SELLER_GRID',
    name: 'Koleksi Produk Terlaris (Best Seller Grid)',
    code: 'bestseller_grid',
    category: 'Katalog & Showcase',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 850,
    systemDependency: 'Storefront Aggregation Engine',
    latencyRating: 'Fast (<25ms)',
    description: 'Grid katalog produk unggulan otomatis berbasis volume pesanan tertinggi toko dengan dukungan quick-add to cart.',
    defaultSchema: {
      maxProducts: 12,
      columnsDesktop: 4,
      enableQuickViewModal: true,
      enableWishlistToggle: true,
      showRatingStars: true,
      discountBadgePosition: 'top_left'
    }
  },
  {
    key: 'TESTIMONIAL_VERIFIED_REVIEW',
    name: 'Ulasan Pembeli Terverifikasi (Testimonials)',
    code: 'verified_testimonials',
    category: 'Social Proof',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 590,
    systemDependency: 'Order Verification Hash',
    latencyRating: 'Fast (<15ms)',
    description: 'Ulasan pembeli asli yang diverifikasi oleh sistem escrow Indovia dengan foto produk dan rating bintang.',
    defaultSchema: {
      minRatingToShow: 4,
      maxTestimonials: 6,
      layout: 'carousel_cards',
      showVerifiedBuyerBadge: true,
      allowCustomerPhotoZoom: true
    }
  },
  {
    key: 'INSTAGRAM_SOCIAL_FEED',
    name: 'Galeri Feed Instagram (Social Commerce)',
    code: 'instagram_feed',
    category: 'Media Sosial & Integrasi',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 445,
    systemDependency: 'Meta Graph API v19.0',
    latencyRating: 'External API (~180ms)',
    description: 'Sinkronisasi foto feed Instagram toko merchant secara live dengan pin tautan langsung belanja per foto.',
    defaultSchema: {
      maxPosts: 8,
      gridColumns: 4,
      showLikeCommentCount: true,
      openInNewTab: true,
      cacheDurationMinutes: 60,
      enableShoppableProductTag: true
    }
  },
  {
    key: 'NEWSLETTER_SUBSCRIPTION_HUB',
    name: 'Form Langganan Email (Newsletter Hub)',
    code: 'newsletter_hub',
    category: 'Retensi & Marketing',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 710,
    systemDependency: 'Brevo / Mailgun Webhook',
    latencyRating: 'Fast (<40ms)',
    description: 'Formulir penangkapan prospek email pembeli dengan kupon diskon selamat datang otomatis.',
    defaultSchema: {
      headline: 'Dapatkan Voucher Diskon 15% Untuk Belanja Pertama Anda!',
      subheadline: 'Berlangganan kabar promo eksklusif, rilis produk baru, dan tips gaya hidup.',
      instantCouponCode: 'WELCOME15',
      gdprPrivacyConsentText: 'Saya menyetujui pemrosesan data untuk pengiriman buletin promosi toko.',
      submitButtonText: 'Klaim Diskon Saya'
    }
  },
  {
    key: 'BLOG_COMMERCE_INTEGRATED',
    name: 'Artikel & Edukasi Produk (Blog Commerce)',
    code: 'blog_commerce',
    category: 'Konten & SEO Toko',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 380,
    systemDependency: 'SEO Content Indexer',
    latencyRating: 'Fast (<20ms)',
    description: 'Modul cuplikan postingan blog di beranda untuk memperkuat otoritas SEO Google dan mendidik calon pembeli.',
    defaultSchema: {
      maxArticles: 3,
      showPublishDate: true,
      showEstimatedReadingTime: true,
      attachRelatedProductsBelowArticle: true,
      cardLayout: 'modern_compact'
    }
  },
  {
    key: 'LOOKBOOK_EDITORIAL_SHOPPING',
    name: 'Lookbook Majalah Foto Produk (Lookbook 1-3)',
    code: 'lookbook_editorial',
    category: 'Showcase Editorial',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 260,
    systemDependency: 'Interactive Hotspot Engine',
    latencyRating: 'Fast (<15ms)',
    description: 'Halaman dan blok majalah foto produk interaktif di mana pembeli bisa mengklik titik baju yang dipakai model untuk langsung beli.',
    defaultSchema: {
      maxHotspotsPerImage: 5,
      pulseAnimationColor: '#ff6c2f',
      showPriceTagOnHover: true,
      autoOpenCartDrawerOnClick: true
    }
  },
  {
    key: 'MULTI_STORE_LOCATIONS_MAP',
    name: 'Direktori Cabang Toko Fisik (Store Locations)',
    code: 'store_locations',
    category: 'Omnichannel & Offline',
    isEnabled: true,
    allowMerchantToggle: true,
    activeUsageCount: 215,
    systemDependency: 'Google Maps Places API',
    latencyRating: 'External API (~120ms)',
    description: 'Halaman peta dan daftar lokasi cabang toko fisik merchant lengkap dengan jam operasional, alamat, dan tombol rute jalan.',
    defaultSchema: {
      mapDefaultZoom: 12,
      showOperatingHours: true,
      enableDirectionButton: true,
      filterByCityEnabled: true
    }
  },
  {
    key: 'PRODUCT_SINGLE_GALLERY_ENGINE',
    name: 'Mesin Tata Letak Detail Produk (24 Layouts)',
    code: 'product_single_engine',
    category: 'Layout Detail Produk',
    isEnabled: true,
    allowMerchantToggle: false,
    activeUsageCount: 850,
    systemDependency: 'Core Product Page Renderer',
    latencyRating: 'Ultra Fast (<5ms)',
    description: 'Mesin master yang merender 24 variasi tata letak detail produk (sticky thumbnail, image zoom, varian swatch, dan review section).',
    defaultSchema: {
      enableGlassZoom: true,
      enableStickyAddToCart: true,
      showLowStockWarningThreshold: 5,
      showEstimatedDeliveryDays: true,
      enableSocialShareButtons: true
    }
  }
];

export const formatRupiah = (val) => {
  if (!val || val === 0) return 'Gratis (Free)';
  return new Intl.NumberFormat('id-ID', {
    style: 'currency',
    currency: 'IDR',
    minimumFractionDigits: 0
  }).format(val);
};

// 24 PRODUCT SINGLE LAYOUTS REGISTRY
export const initialProductLayouts = [
  {
    "id": "product-layout-01",
    "layoutNumber": "Layout 01",
    "name": "Product Single 1",
    "styleType": "Sticky Gallery Grid (Classic)",
    "category": "Grid & Sticky",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": true,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 540,
    "demoPath": "/product-single",
    "thumbnail": "/assets/imgs/page/product/img.png",
    "description": "Tata letak klasik dengan galeri gambar sticky di sisi kiri dan panel informasi produk, tombol beli, serta swatch warna di sisi kanan.",
    "features": [
      "Sticky Thumbnail Gallery",
      "Magnifier Zoom 2x",
      "Color Swatches",
      "Stock Scarcity Tag",
      "Social Share Icons"
    ]
  },
  {
    "id": "product-layout-02",
    "layoutNumber": "Layout 02",
    "name": "Product Single 2",
    "styleType": "Thumbnail Slider Left + Sticky Info",
    "category": "Slider & Carousel",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 390,
    "demoPath": "/product-single-2",
    "thumbnail": "/assets/imgs/page/product/img2.png",
    "description": "Slider thumbnail vertikal di sebelah kiri gambar utama dengan navigasi panah halus dan panel beli compact.",
    "features": [
      "Vertical Thumb Carousel",
      "Smooth Click-to-Zoom",
      "Variant Button Pills",
      "Estimated Courier Calc"
    ]
  },
  {
    "id": "product-layout-03",
    "layoutNumber": "Layout 03",
    "name": "Product Single 3",
    "styleType": "Vertical Scroll Multi-Image Feed",
    "category": "Grid & Sticky",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 310,
    "demoPath": "/product-single-3",
    "thumbnail": "/assets/imgs/page/product/thumnb.png",
    "description": "Alur gambar bertingkat ke bawah (infinite vertical feed) dengan panel checkout sticky yang mengikuti scroll pembeli.",
    "features": [
      "Stacked Vertical Feed",
      "Sticky Purchase Sidebar",
      "Real-Time Stock Counter",
      "Size Chart Popover"
    ]
  },
  {
    "id": "product-layout-04",
    "layoutNumber": "Layout 04",
    "name": "Product Single 4",
    "styleType": "Fullwidth Hero Showcase + Side Details",
    "category": "Fullwidth & Editorial",
    "status": "PREMIUM",
    "price": 99000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 240,
    "demoPath": "/product-single-4",
    "thumbnail": "/assets/imgs/page/product/thumnb2.png",
    "description": "Tampilan gambar produk beresolusi ultra-lebar dengan transisi editorial mewah, cocok untuk busana haute-couture.",
    "features": [
      "Fullwidth Hero Image",
      "Editorial Specs Typography",
      "Sticky Add to Cart Bar",
      "High-Resolution Lightbox"
    ]
  },
  {
    "id": "product-layout-05",
    "layoutNumber": "Layout 05",
    "name": "Product Single 5",
    "styleType": "Clean Minimalist (Light Focus)",
    "category": "Minimalist & Clean",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 280,
    "demoPath": "/product-single-5",
    "thumbnail": "/assets/imgs/page/product/thumnb3.png",
    "description": "Estetika minimalis tanpa distraksi dengan ruang putih luas, fokus tajam pada detail produk dan tombol beli jelas.",
    "features": [
      "Distraction-Free Layout",
      "Clean Typography",
      "Quick Quantity Selector",
      "Instant Buy Now Button"
    ]
  },
  {
    "id": "product-layout-06",
    "layoutNumber": "Layout 06",
    "name": "Product Single 6",
    "styleType": "Luxury Dark Mode Studio View",
    "category": "Luxury & Dark",
    "status": "PREMIUM",
    "price": 129000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 215,
    "demoPath": "/product-single-6",
    "thumbnail": "/assets/imgs/page/product/thumnb4.png",
    "description": "Mode gelap sinematik untuk produk mewah (arloji, perhiasan emas, gadget premium) dengan efek bayangan mendalam.",
    "features": [
      "OLED Dark Mode",
      "Gold/Silver Accent Badges",
      "High-Value Escrow Badge",
      "Certificate Verification Link"
    ]
  },
  {
    "id": "product-layout-07",
    "layoutNumber": "Layout 07",
    "name": "Product Single 7",
    "styleType": "Accordion Specifications Drawer",
    "category": "Specialty & Niche",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 195,
    "demoPath": "/product-single-7",
    "thumbnail": "/assets/imgs/page/product/thumnb5.png",
    "description": "Struktur detail produk dengan panel accordion lipat untuk spesifikasi bahan, instruksi pencucian, dan garansi.",
    "features": [
      "Collapsible Accordion Tabs",
      "Material Care Instructions",
      "Warranty Info Drawer",
      "FAQ Dropdown Inside"
    ]
  },
  {
    "id": "product-layout-08",
    "layoutNumber": "Layout 08",
    "name": "Product Single 8",
    "styleType": "Tabbed Review & Size Recommender",
    "category": "Reviews & Community",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 260,
    "demoPath": "/product-single-8",
    "thumbnail": "/assets/imgs/page/product/img.png",
    "description": "Fokus kuat pada bukti sosial dengan galeri ulasan berfoto, sistem bintang rating terverifikasi, dan rekomendasi ukuran.",
    "features": [
      "Photo Review Carousel",
      "Verified Buyer Tag",
      "Interactive Rating Filter",
      "Height/Weight Size Advisor"
    ]
  },
  {
    "id": "product-layout-09",
    "layoutNumber": "Layout 09",
    "name": "Product Single 9",
    "styleType": "Split Screen 50/50 Dual Column",
    "category": "Grid & Sticky",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 180,
    "demoPath": "/product-single-9",
    "thumbnail": "/assets/imgs/page/product/img2.png",
    "description": "Komposisi seimbang dua kolom 50:50 dengan scroll independen pada gambar dan panel ringkasan pembelian.",
    "features": [
      "Dual Independent Scroll",
      "High-Impact Product Photography",
      "Quick Buy Sticky Bar",
      "Multi-Currency Ready"
    ]
  },
  {
    "id": "product-layout-10",
    "layoutNumber": "Layout 10",
    "name": "Product Single 10",
    "styleType": "Lookbook Hotspot Tagged View",
    "category": "Editorial & Lookbook",
    "status": "PREMIUM",
    "price": 149000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 230,
    "demoPath": "/product-single-10",
    "thumbnail": "/assets/imgs/page/product/thumnb.png",
    "description": "Foto lookbook model dengan pin interaktif (hotspots) yang dapat diklik untuk membeli set pakaian lengkap.",
    "features": [
      "Clickable Hotspot Pins",
      "Shop The Entire Look Modal",
      "Bundle Discount Calculator",
      "Instagram Feed Sync"
    ]
  },
  {
    "id": "product-layout-11",
    "layoutNumber": "Layout 11",
    "name": "Product Single 11",
    "styleType": "Masonry Grid Gallery Layout",
    "category": "Grid & Sticky",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 170,
    "demoPath": "/product-single-11",
    "thumbnail": "/assets/imgs/page/product/thumnb2.png",
    "description": "Susunan galeri foto tidak simetris (masonry) untuk memperlihatkan sudut pandang produk dari berbagai jarak.",
    "features": [
      "Masonry Visual Layout",
      "Lightbox Zoom Preview",
      "Variant Click Sync",
      "Sticky Buy Button"
    ]
  },
  {
    "id": "product-layout-12",
    "layoutNumber": "Layout 12",
    "name": "Product Single 12",
    "styleType": "Interactive 360 Orbit Preview",
    "category": "Specialty & Niche",
    "status": "PREMIUM",
    "price": 199000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 295,
    "demoPath": "/product-single-12",
    "thumbnail": "/assets/imgs/page/product/thumnb3.png",
    "description": "Visualizer produk interaktif 360 derajat yang dapat diputar dengan drag kursor mouse atau sentuhan jari di layar hp.",
    "features": [
      "360 Degree Drag Rotation",
      "High-Res Frame Stacking",
      "Autoplay Spin Mode",
      "Mobile Gyroscope Support"
    ]
  },
  {
    "id": "product-layout-13",
    "layoutNumber": "Layout 13",
    "name": "Product Single 13",
    "styleType": "Video Feature Hero Showcase",
    "category": "Fullwidth & Editorial",
    "status": "PREMIUM",
    "price": 119000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 185,
    "demoPath": "/product-single-13",
    "thumbnail": "/assets/imgs/page/product/thumnb4.png",
    "description": "Pemutar video produk otomatis di header dengan tombol play suara, cocok untuk demonstrasi pemakaian barang.",
    "features": [
      "Looping Background Video",
      "Mute/Unmute Quick Toggle",
      "Picture-in-Picture Mode",
      "Video Chapter Timestamps"
    ]
  },
  {
    "id": "product-layout-14",
    "layoutNumber": "Layout 14",
    "name": "Product Single 14",
    "styleType": "Modern Card Floating Badges",
    "category": "Minimalist & Clean",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 220,
    "demoPath": "/product-single-14",
    "thumbnail": "/assets/imgs/page/product/thumnb5.png",
    "description": "Kartu produk melayang dengan badge sertifikasi resmi (SNI, BPOM, Halal, Garansi Resmi 1 Tahun).",
    "features": [
      "Floating Card Shadow",
      "Trust Badge Showcase",
      "Official Warranty Tag",
      "Buyer Protection Guarantee"
    ]
  },
  {
    "id": "product-layout-15",
    "layoutNumber": "Layout 15",
    "name": "Product Single 15",
    "styleType": "Beauty & Skincare Routine Layout",
    "category": "Specialty & Niche",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 340,
    "demoPath": "/product-single-15",
    "thumbnail": "/assets/imgs/page/product/img.png",
    "description": "Khusus industri kosmetik dan skincare: dilengkapi langkah rutin harian (Step 1-4), tabel bahan aktif, dan uji klinis.",
    "features": [
      "Skincare Step Indicator",
      "Key Ingredients Highlighting",
      "Dermatologist Tested Badge",
      "Before/After Comparison"
    ]
  },
  {
    "id": "product-layout-16",
    "layoutNumber": "Layout 16",
    "name": "Product Single 16",
    "styleType": "Electronics Tech Spec Comparison Layout",
    "category": "Specialty & Niche",
    "status": "PREMIUM",
    "price": 139000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 380,
    "demoPath": "/product-single-16",
    "thumbnail": "/assets/imgs/page/product/img2.png",
    "description": "Khusus produk elektronik dan gadget: tabel komparasi spek teknis, opsi cicilan bank, dan pilihan varian RAM/Storage.",
    "features": [
      "Technical Spec Grid",
      "RAM & SSD Variant Matrix",
      "0% Installment Simulator",
      "Serial Number Checker"
    ]
  },
  {
    "id": "product-layout-17",
    "layoutNumber": "Layout 17",
    "name": "Product Single 17",
    "styleType": "Food Nutrition & Ingredients Table",
    "category": "Specialty & Niche",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 250,
    "demoPath": "/product-single-17",
    "thumbnail": "/assets/imgs/page/product/thumnb.png",
    "description": "Etalase makanan dan minuman dengan label nilai gizi resmi (nutrition facts), sertifikat halal, dan tanggal kadaluarsa.",
    "features": [
      "Nutrition Facts Panel",
      "Allergen Warning Alert",
      "Instant Courier Delivery Only Tag",
      "Keep Refrigerated Notice"
    ]
  },
  {
    "id": "product-layout-18",
    "layoutNumber": "Layout 18",
    "name": "Product Single 18",
    "styleType": "Fashion Fit & Size Conversion Layout",
    "category": "Grid & Sticky",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 290,
    "demoPath": "/product-single-18",
    "thumbnail": "/assets/imgs/page/product/thumnb2.png",
    "description": "Khusus pakaian dan busana: konversi ukuran internasional (EU, US, UK, CM), petunjuk fitting model, dan panduan lingkar dada.",
    "features": [
      "Interactive Size Converter",
      "Model Height & Size Worn",
      "Fabric Stretch Meter",
      "Virtual Fitting Room Button"
    ]
  },
  {
    "id": "product-layout-19",
    "layoutNumber": "Layout 19",
    "name": "Product Single 19",
    "styleType": "Eco-Friendly Plants Care Notes View",
    "category": "Specialty & Niche",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 165,
    "demoPath": "/product-single-19",
    "thumbnail": "/assets/imgs/page/product/thumnb3.png",
    "description": "Khusus tanaman hias dan bibit: petunjuk penyiraman, kebutuhan sinar matahari, tingkat kesulitan perawatan, dan opsi pot.",
    "features": [
      "Sun & Water Meter Badges",
      "Care Difficulty Rating",
      "Pot Ceramic Color Swatches",
      "Plant Safety for Pets Badge"
    ]
  },
  {
    "id": "product-layout-20",
    "layoutNumber": "Layout 20",
    "name": "Product Single 20",
    "styleType": "Bikes & Sports Technical Blueprint",
    "category": "Specialty & Niche",
    "status": "PREMIUM",
    "price": 159000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 175,
    "demoPath": "/product-single-20",
    "thumbnail": "/assets/imgs/page/product/thumnb4.png",
    "description": "Khusus sepeda, alat gym, dan perlengkapan olahraga: diagram blueprint geometri frame, spesifikasi groupset, dan rekomendasi tinggi badan.",
    "features": [
      "Frame Geometry Blueprint",
      "Rider Height (cm) Chart",
      "Component Groupset Selector",
      "Assembly Difficulty Rating"
    ]
  },
  {
    "id": "product-layout-21",
    "layoutNumber": "Layout 21",
    "name": "Product Single 21",
    "styleType": "Baby & Maternity Safety Checklist View",
    "category": "Specialty & Niche",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 210,
    "demoPath": "/product-single-21",
    "thumbnail": "/assets/imgs/page/product/thumnb5.png",
    "description": "Khusus perlengkapan bayi dan ibu hamil: sertifikasi bebas BPA, bahan katun organik lembut, dan checklist kebutuhan rumah sakit.",
    "features": [
      "BPA-Free Safety Badge",
      "Age Group Selector (0-3M, 3-6M)",
      "Hospital Bag Checklist Tag",
      "Gift Wrapping Service Add-on"
    ]
  },
  {
    "id": "product-layout-22",
    "layoutNumber": "Layout 22",
    "name": "Product Single 22",
    "styleType": "Fitness High-Impact Action Showcase",
    "category": "Fullwidth & Editorial",
    "status": "PREMIUM",
    "price": 119000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 195,
    "demoPath": "/product-single-22",
    "thumbnail": "/assets/imgs/page/product/img.png",
    "description": "Layout energik dengan visual atlet bergerak, badge material anti-keringat (breathable), dan penawaran bundle suplemen.",
    "features": [
      "Action Photography Layout",
      "Breathable Fabric Spec Tag",
      "Frequently Bought Together Bundle",
      "Coach Video Review"
    ]
  },
  {
    "id": "product-layout-23",
    "layoutNumber": "Layout 23",
    "name": "Product Single 23",
    "styleType": "Travel Gear Capacity & Luggage Dimensions",
    "category": "Specialty & Niche",
    "status": "PREMIUM",
    "price": 129000,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 180,
    "demoPath": "/product-single-23",
    "thumbnail": "/assets/imgs/page/product/img2.png",
    "description": "Khusus koper, ransel, dan tas travel: simulator muatan liter, cek kepatuhan ukuran bagasi kabin maskapai, dan fitur keamanan TSA.",
    "features": [
      "Luggage Liter Capacity Bar",
      "Cabin Size Airline Check",
      "TSA Lock Demonstration",
      "Lifetime Warranty Badge"
    ]
  },
  {
    "id": "product-layout-24",
    "layoutNumber": "Layout 24",
    "name": "Product Single 24",
    "styleType": "Artisan Coffee Flavor Notes Wheel Layout",
    "category": "Specialty & Niche",
    "status": "PUBLIC_FREE",
    "price": 0,
    "isDefault": false,
    "isGlobalEnabled": true,
    "activeMerchantsCount": 275,
    "demoPath": "/product-single-24",
    "thumbnail": "/assets/imgs/page/product/thumnb.png",
    "description": "Khusus kopi spesialti dan teh artisan: diagram roda rasa (flavor notes), tingkat sangrai (roast level), dan pilihan gilingan biji kopi.",
    "features": [
      "Flavor Notes Wheel Diagram",
      "Roast Level Meter",
      "Grind Size Option Selector",
      "Roasting Date Freshness Seal"
    ]
  }
];

// STORE AUXILIARY PAGES & SYSTEM ROUTES REGISTRY
export const initialStorePages = [
  {
    "id": "page-cart",
    "name": "Your Cart",
    "group": "COMMERCE",
    "groupLabel": "Transaksi & Checkout",
    "routePath": "/cart",
    "thumbnail": "/assets/imgs/page/cart/sp.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": false,
    "activeUsageCount": 850,
    "description": "Keranjang belanja dinamis dengan kalkulasi kupon diskon instan, estimasi ongkos kirim, dan proteksi asuransi checkout.",
    "features": [
      "Instant Coupon Apply",
      "Free Shipping Progress Bar",
      "Quantity Auto-Recalculate",
      "Cross-sell Product Slider"
    ],
    "seoTitle": "Keranjang Belanja | Indovia Store"
  },
  {
    "id": "page-checkout",
    "name": "Checkout",
    "group": "COMMERCE",
    "groupLabel": "Transaksi & Checkout",
    "routePath": "/checkout",
    "thumbnail": "/assets/imgs/page/cart/sp2.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": false,
    "activeUsageCount": 850,
    "description": "Halaman pembayaran checkout terpadu dengan integrasi Midtrans / Xendit, QRIS 1-detik, Virtual Account, dan Escrow holding.",
    "features": [
      "One-Page Checkout",
      "Multi-Carrier Realtime Rates",
      "Escrow Platform Guarantee",
      "Automated Invoice Generator"
    ],
    "seoTitle": "Pembayaran & Checkout | Indovia Store"
  },
  {
    "id": "page-about-1",
    "name": "About Us",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/about-us-1",
    "thumbnail": "/assets/imgs/page/about1/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 720,
    "description": "Profil brand toko dengan narasi visi-misi, lini masa pencapaian, dan etalase nilai keunggulan produk.",
    "features": [
      "Company Timeline History",
      "Brand Value Icons",
      "Customer Statistics Counter",
      "Founder Story Letter"
    ],
    "seoTitle": "Tentang Kami | Indovia Store"
  },
  {
    "id": "page-about-2",
    "name": "About Us 2",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/about-us-2",
    "thumbnail": "/assets/imgs/page/about1/team.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 430,
    "description": "Tata letak profil tim & kantor dengan fokus pada budaya kerja, galeri kantor, dan etos kerja perusahaan.",
    "features": [
      "Team Members Grid",
      "Office Gallery Carousel",
      "Core Principles Accordion",
      "Video Interview Embed"
    ],
    "seoTitle": "Tim & Profil Kami | Indovia Store"
  },
  {
    "id": "page-store-location",
    "name": "Store Location",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/store-location",
    "thumbnail": "/assets/imgs/page/about1/about1.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 380,
    "description": "Peta interaktif cabang toko fisik offline merchant dengan jam operasional, nomor telepon, dan rute Google Maps.",
    "features": [
      "Interactive Map Embed",
      "Store Operating Hours",
      "Storefront Photo Slider",
      "Direct WhatsApp Branch"
    ],
    "seoTitle": "Lokasi Toko Fisik | Indovia Store"
  },
  {
    "id": "page-contact",
    "name": "Contact Us",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/contact",
    "thumbnail": "/assets/imgs/page/about1/about2.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 810,
    "description": "Formulir kontak langsung terhubung ke email customer support toko dan widget chat WhatsApp resmi.",
    "features": [
      "Spam-Protected Contact Form",
      "Business Inquiries Selector",
      "WhatsApp Direct Redirect",
      "Helpdesk Ticket Integration"
    ],
    "seoTitle": "Hubungi Kami | Indovia Store"
  },
  {
    "id": "page-careers",
    "name": "Job and Carrers",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/carrers",
    "thumbnail": "/assets/imgs/page/about1/about3.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 290,
    "description": "Portal karir dan lowongan pekerjaan untuk brand merchant yang sedang memperluas tim operasional atau toko.",
    "features": [
      "Job Vacancies Listing",
      "CV Upload Form",
      "Company Culture Highlights",
      "Employee Perks & Benefits"
    ],
    "seoTitle": "Karir & Lowongan Kerja | Indovia Store"
  },
  {
    "id": "page-custome-service",
    "name": "Custome Services",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/custome-service",
    "thumbnail": "/assets/imgs/page/about1/about4.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 560,
    "description": "Pusat bantuan pelanggan untuk syarat garansi, panduan penukaran barang, dan kebijakan retur 14 hari.",
    "features": [
      "Return & Refund Policy",
      "Live Warranty Checker",
      "Shipping Tracking Lookup",
      "Support Hotline Hours"
    ],
    "seoTitle": "Layanan Pelanggan & Garansi | Indovia Store"
  },
  {
    "id": "page-faq",
    "name": "FAQs page",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/faq",
    "thumbnail": "/assets/imgs/page/about1/team2.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 740,
    "description": "Daftar pertanyaan yang sering diajukan (FAQ) dengan pencarian kata kunci dan kategori accordion rapi.",
    "features": [
      "Searchable FAQ Input",
      "Categorized Tabs (Order, Pay, Ship)",
      "Accordion Answer Toggle",
      "Still Need Help CTA"
    ],
    "seoTitle": "Pertanyaan Umum (FAQ) | Indovia Store"
  },
  {
    "id": "page-store-locations",
    "name": "Store Locations",
    "group": "BRAND",
    "groupLabel": "Informasi & Perusahaan",
    "routePath": "/store-locations",
    "thumbnail": "/assets/imgs/page/about1/about1.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 380,
    "description": "Direktori multi-cabang gerai offline merchant di berbagai kota dengan filter provinsi dan integrasi Google Maps.",
    "features": [
      "Multi-Branch Store Directory",
      "City & Province Filters",
      "Google Maps Route Direction",
      "Branch Contact & Operating Hours"
    ],
    "seoTitle": "Direktori Cabang Toko | Indovia Store"
  },
  {
    "id": "page-lookbook-1",
    "name": "Lookbook 1",
    "group": "LOOKBOOK",
    "groupLabel": "Visual Lookbook",
    "routePath": "/lookbook",
    "thumbnail": "/assets/imgs/page/lookbook/img.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 310,
    "description": "Galeri fotografi editorial gaya busana dengan tag produk interaktif untuk belanja langsung dari inspirasi model.",
    "features": [
      "Shoppable Lookbook Grid",
      "Hover Pin Hotspots",
      "High-Resolution Lightbox",
      "Seasonal Lookbook Filter"
    ],
    "seoTitle": "Lookbook Editorial Vol. 1 | Indovia Store"
  },
  {
    "id": "page-lookbook-2",
    "name": "Lookbook 2",
    "group": "LOOKBOOK",
    "groupLabel": "Visual Lookbook",
    "routePath": "/lookbook-2",
    "thumbnail": "/assets/imgs/page/lookbook/img2.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 220,
    "description": "Tata letak lookbook bergaya majalah fashion dengan tata letak asimetris dan kutipan desainer.",
    "features": [
      "Magazine Editorial Spread",
      "Full Bleed Photography",
      "Designer Quotes Callout",
      "Quick Add Look To Bag"
    ],
    "seoTitle": "Lookbook Editorial Vol. 2 | Indovia Store"
  },
  {
    "id": "page-lookbook-3",
    "name": "Lookbook 3",
    "group": "LOOKBOOK",
    "groupLabel": "Visual Lookbook",
    "routePath": "/lookbook-3",
    "thumbnail": "/assets/imgs/page/lookbook/img3.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 180,
    "description": "Tampilan lookbook slider carousel horizontal dengan transisi sinematik untuk koleksi pakaian musiman.",
    "features": [
      "Horizontal Panoramic Carousel",
      "Smooth Parallax Scrolling",
      "Model Fit Details",
      "Collection Video Embed"
    ],
    "seoTitle": "Lookbook Editorial Vol. 3 | Indovia Store"
  },
  {
    "id": "page-shop-left-filter",
    "name": "Shop Left Filter",
    "group": "SHOP",
    "groupLabel": "Katalog Belanja",
    "routePath": "/shop-left-filter",
    "thumbnail": "/assets/imgs/page/homepage1/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 710,
    "description": "Halaman katalog utama dengan sidebar filter di sebelah kiri (kategori, rentang harga slider, warna, dan ukuran).",
    "features": [
      "Left Filter Sidebar",
      "Price Range Slider",
      "Color & Size Badges",
      "Pagination Controls"
    ],
    "seoTitle": "Katalog Belanja (Left Filter) | Indovia Store"
  },
  {
    "id": "page-shop-top-filter",
    "name": "Shop Top Filter",
    "group": "SHOP",
    "groupLabel": "Katalog Belanja",
    "routePath": "/shop-top-filter",
    "thumbnail": "/assets/imgs/page/homepage2/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 520,
    "description": "Katalog belanja modern dengan filter horizontal di bagian atas produk untuk memaksimalkan lebar etalase produk.",
    "features": [
      "Top Horizontal Filter Bar",
      "Fullwidth 4-Col Grid",
      "Dropdown Sort By",
      "Quick View Modal"
    ],
    "seoTitle": "Katalog Belanja (Top Filter) | Indovia Store"
  },
  {
    "id": "page-shop-canvas-filter",
    "name": "Shop Canvas Filter",
    "group": "SHOP",
    "groupLabel": "Katalog Belanja",
    "routePath": "/shop-canvas-filter",
    "thumbnail": "/assets/imgs/page/homepage3/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 460,
    "description": "Filter offcanvas slide-out dari samping layar, sangat ramah untuk pengguna smartphone dan tablet.",
    "features": [
      "Offcanvas Slide Drawer",
      "Mobile-First UX",
      "Filter Counter Badge",
      "Clear All Filters Button"
    ],
    "seoTitle": "Katalog Belanja (Canvas Filter) | Indovia Store"
  },
  {
    "id": "page-shop-load-more",
    "name": "Shop Load More",
    "group": "SHOP",
    "groupLabel": "Katalog Belanja",
    "routePath": "/shop-load-more",
    "thumbnail": "/assets/imgs/page/homepage4/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 390,
    "description": "Katalog dengan tombol muat lebih banyak (Load More) yang memuat produk tambahan tanpa reload halaman.",
    "features": [
      "AJAX Load More Button",
      "Progress Products Count",
      "Smooth Append Animation",
      "No Page Reload"
    ],
    "seoTitle": "Katalog Belanja (Load More) | Indovia Store"
  },
  {
    "id": "page-shop-infinity",
    "name": "Shop Infinity Scrolling",
    "group": "SHOP",
    "groupLabel": "Katalog Belanja",
    "routePath": "/shop-infinity-scrolling",
    "thumbnail": "/assets/imgs/page/homepage5/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 340,
    "description": "Scroll tanpa henti (infinite scroll) yang otomatis memuat produk baru saat pengunjung scroll ke dasar halaman.",
    "features": [
      "Automatic Infinite Scroll",
      "Skeleton Loader While Fetching",
      "Back to Top Floating Button",
      "Scroll Position Memory"
    ],
    "seoTitle": "Katalog Belanja (Infinite Scroll) | Indovia Store"
  },
  {
    "id": "page-blog-grid",
    "name": "Blog Grid 1",
    "group": "BLOG",
    "groupLabel": "Blog & Artikel",
    "routePath": "/blog-grid",
    "thumbnail": "/assets/imgs/page/blog/img1.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 480,
    "description": "Koleksi artikel tips fashion, berita promo, dan panduan belanja dengan kartu grid 3 kolom simetris.",
    "features": [
      "3-Column Article Grid",
      "Author & Date Badges",
      "Reading Time Calculator",
      "Category Tag Pills"
    ],
    "seoTitle": "Blog Grid 1 | Indovia Store"
  },
  {
    "id": "page-blog-masonry",
    "name": "Blog Grid 2",
    "group": "BLOG",
    "groupLabel": "Blog & Artikel",
    "routePath": "/blog-masonry",
    "thumbnail": "/assets/imgs/page/blog/img3.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 360,
    "description": "Katalog artikel gaya dinamis (Masonry grid) yang menyesuaikan tinggi gambar secara organik dan estetik.",
    "features": [
      "Masonry Fluid Grid Layout",
      "Category Filter Pills",
      "Hover Overlay Preview",
      "Infinite Article Loader"
    ],
    "seoTitle": "Blog Grid 2 (Masonry) | Indovia Store"
  },
  {
    "id": "page-blog-list",
    "name": "Blog List",
    "group": "BLOG",
    "groupLabel": "Blog & Artikel",
    "routePath": "/blog-list",
    "thumbnail": "/assets/imgs/page/blog/img2.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 330,
    "description": "Daftar artikel format vertikal memanjang dengan ringkasan cuplikan teks dan thumbnail samping.",
    "features": [
      "Vertical List Layout",
      "Sidebar Recent Posts",
      "Newsletter Subscription Box",
      "Tag Cloud Widget"
    ],
    "seoTitle": "Arsip Artikel Blog List | Indovia Store"
  },
  {
    "id": "page-blog-single",
    "name": "Single Post",
    "group": "BLOG",
    "groupLabel": "Blog & Artikel",
    "routePath": "/blog-single",
    "thumbnail": "/assets/imgs/page/blog/single.png",
    "isGlobalEnabled": true,
    "showInNavigation": true,
    "allowMerchantToggle": true,
    "activeUsageCount": 480,
    "description": "Halaman baca artikel lengkap dengan tipografi nyaman, galeri gambar di dalam teks, dan kolom komentar pembaca.",
    "features": [
      "Reading Experience Typography",
      "Social Share Floating Bar",
      "Related Articles Carousel",
      "Interactive Comment Section"
    ],
    "seoTitle": "Detail Artikel Single Post | Indovia Store"
  },
  {
    "id": "page-maintenance",
    "name": "Maintenance",
    "group": "SYSTEM",
    "groupLabel": "Sistem & Utilitas",
    "routePath": "/maintenance",
    "thumbnail": "/assets/imgs/page/maintenance/banner.png",
    "isGlobalEnabled": false,
    "showInNavigation": false,
    "allowMerchantToggle": true,
    "activeUsageCount": 15,
    "description": "Halaman pemeliharaan sistem toko saat merchant sedang merenovasi katalog, stok opname, atau integrasi sistem.",
    "features": [
      "Maintenance Notice Banner",
      "Estimated Online Countdown",
      "Emergency WhatsApp Contact",
      "Notify Me Email Form"
    ],
    "seoTitle": "Situs Sedang Dalam Pemeliharaan | Indovia Store"
  },
  {
    "id": "page-coming-soon",
    "name": "Comming soon",
    "group": "SYSTEM",
    "groupLabel": "Sistem & Utilitas",
    "routePath": "/comming-soon",
    "thumbnail": "/assets/imgs/page/commingsoon/banner.png",
    "isGlobalEnabled": true,
    "showInNavigation": false,
    "allowMerchantToggle": true,
    "activeUsageCount": 45,
    "description": "Halaman hitung mundur pembukaan toko baru atau peluncuran lini produk eksklusif dengan pendaftaran email.",
    "features": [
      "Flip Clock Launch Countdown",
      "Early-Bird Voucher Signup",
      "Social Media Follow Links",
      "Teaser Video Background"
    ],
    "seoTitle": "Segera Hadir | Indovia Store"
  },
  {
    "id": "page-404",
    "name": "404 Page",
    "group": "SYSTEM",
    "groupLabel": "Sistem & Utilitas",
    "routePath": "/pages-404",
    "thumbnail": "/assets/imgs/page/404/404.svg",
    "isGlobalEnabled": true,
    "showInNavigation": false,
    "allowMerchantToggle": false,
    "activeUsageCount": 850,
    "description": "Halaman penanganan rute tidak ditemukan dengan tombol kembali ke beranda dan rekomendasi produk populer.",
    "features": [
      "Friendly 404 Illustration",
      "Return to Home Button",
      "Search Bar Re-attempt",
      "Trending Categories Quicklinks"
    ],
    "seoTitle": "404 Halaman Tidak Ditemukan | Indovia Store"
  }
];
